name: un-cascade
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - flask>=3.0.0
  - requests>=2.31.0
  - plotly>=5.18.0
  - pandas>=2.1.3
  # pip is included just in case you ever need a package not on conda-forge
  - pip